name: Prepare and Deploy Artifact


on:
  workflow_dispatch:  
    inputs:
        PageName:
          description: 'Page Name'
          required: true
          default: 'latest'
        PagePipelineID:
          description: 'Page Pipeline ID'
          required: true
          default: 'latest'
jobs:
    prepare_deploy_artifact:
        runs-on: ubuntu-latest
        steps:
          # Step 2: Download the artifact generated in build_packages into ./build_packages
          - name: Download Paquete A
            uses: actions/download-artifact@v4
            with:
              name: ${{ github.event.inputs.PageName }}
              path: pages
              repository: Leku2020/owlArchRepo
              run-id: ${{ github.event.inputs.PagePipelineID }}
          - name: List
            run: |
              ls pages
