name: Prepare and Deploy Artifact


on:
  workflow_dispatch:  
    inputs:
        PageName:
          description: 'Page Name'
          required: true
          default: 'latest'
        PagePipelineID:
          description: 'Page Pipeline ID'
          required: true
          default: 'latest'
        PackageName:
          description: 'Package Name'
          required: true
          default: 'latest'
        PackagePipelineID:
          description: 'Package Pipeline ID'
          required: true
          default: 'latest'
jobs:
    prepare_deploy_artifact:
        runs-on: ubuntu-latest
        steps:
          # Step 1: Download the artifact generated in PageGeneration into pages
          - name: Download Pages
            uses: actions/download-artifact@v4
            with:
              name: ${{ github.event.inputs.PageName }}
              github-token: ${{ secrets.GITHUB_TOKEN }}
              path: pages
              repository: ${{ github.repository }}
              run-id: ${{ github.event.inputs.PagePipelineID }}
          # Step 2: Download the artifact generated in build_packages into ./build_packages
          - name: Download Packages
            uses: actions/download-artifact@v4
            with:
              name: ${{ github.event.inputs.PackageName }}
              github-token: ${{ secrets.GITHUB_TOKEN }}
              path: pages
              repository: ${{ github.repository }}
              run-id: ${{ github.event.inputs.PackagePipelineID }}      
          - name: List
            run: |
              ls pages
              
          - name: Upload artifact
            uses: actions/upload-pages-artifact@v3
            with: 
              name: deploy_artifact
              path: pages

    deploy:
      if: github.ref == 'refs/heads/main'
      # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
      permissions:
        contents: read
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: prepare_deploy_artifact
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
          with:
            artifact_name: deploy_artifact