name: Build PKGBUILDs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job 1: Compilación
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build PKGBUILD in Arch Linux Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
            useradd -m builder && echo 'builder:password' | chpasswd && \
            pacman -Sy --noconfirm sudo && \
            echo 'builder ALL=(ALL) NOPASSWD: /usr/bin/pacman' >> /etc/sudoers && \
            pacman -Sy --noconfirm base-devel git && \
            chown -R builder:builder /workspace && \
            su - builder -c '
              find /workspace -type f -name PKGBUILD | while read PKGBUILD; do
                dir=\$(dirname \$PKGBUILD)
                echo \"Building package in \$dir\"
                cd \$dir && makepkg -si --noconfirm && cd -
              done
            '"
            
      - name: Upload packages to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: '**/*.pkg.tar.zst'


  deploy_pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Download packages from build job
        uses: actions/download-artifact@v4
        
      - name: Upload packages to GitHub Pages directory
        run: |
          echo "Creating pkgs/x86_64/extra/brave directory"
          mkdir -p $GITHUB_WORKSPACE/pkgs/x86_64/extra/brave
          echo "Copying brave-browser package to pkgs/x86_64/extra/brave"
          cp pkgs/extra/brave/brave-browser-1.73.91-1-x86_64.pkg.tar.zst $GITHUB_WORKSPACE/pkgs/x86_64/extra/brave/
          ls $GITHUB_WORKSPACE/pkgs/x86_64/extra/brave  # Verifica que el paquete está copiado

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs track "*.pkg.tar.zst" 
          git add .gitattributes
          git commit -m "Track .pkg.tar.zst files with LFS" || echo "No changes to commit"
          
      - name: Commit and push the updated pkgs/x86_64 directory
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "github-actions@github.com"
          message: "Publish new packages to GitHub Pages"
          add: 'pkgs/x86_64/*'

      - name: Deploy to GitHub Pages
        run: |
          echo ${{ github.TEST }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://github.com/Leku2020/owlArchRepo.git
          git add .
          git commit -m "Deploy updated packages"
          git lfs install
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Leku2020/owlArchRepo.git
