name: Build PKGBUILDs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build PKGBUILD in Arch Linux Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
            useradd -m builder && echo 'builder:password' | chpasswd && \
            pacman -Sy --noconfirm sudo && \
            pacman -Sy --noconfirm base-devel git && \
            chown -R builder:builder /workspace && \
            su - builder -c '
              find /workspace -type f -name PKGBUILD | while read PKGBUILD; do
                dir=\$(dirname \$PKGBUILD)
                echo \"Building package in \$dir\"
                cd \$dir && makepkg -si --noconfirm && cd -
              done
            '"

      - name: Upload packages to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: '**/*.pkg.tar.zst'

  deploy_artifact:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download packages from build job
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: './packages'
          
      - name: Upload packages to GitHub Pages directory
        run: |
          echo "Creating pkgs/x86_64 directory"
          mkdir -p $GITHUB_WORKSPACE/pkgs/x86_64
          echo "Copying packages to pkgs/x86_64"
          cp ./packages/*.pkg.tar.zst $GITHUB_WORKSPACE/pkgs/x86_64/
          ls $GITHUB_WORKSPACE/pkgs/x86_64

      - name: Commit and push the updated pkgs/x86_64 directory
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "github-actions@github.com"
          message: "Publish new packages to GitHub Pages"
          add: 'pkgs/x86_64/*'

  # Job 2.2: Despliegue en GitHub Pages
  deploy_pages:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://github.com/Leku2020/owlArchRepo.git
          git add .
          git commit -m "Deploy updated packages"
          git push origin main
