name: Build PKGBUILDs

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build PKGBUILD in Arch Linux Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
            useradd -m builder && echo 'builder:password' | chpasswd && \
            pacman -Sy --noconfirm sudo && \
            echo 'builder ALL=(ALL) NOPASSWD: /usr/bin/pacman' >> /etc/sudoers && \
            pacman -Sy --noconfirm base-devel git && \
            chown -R builder:builder /workspace && \
            su - builder -c '
              find /workspace -type f -name PKGBUILD | while read PKGBUILD; do
                dir=\$(dirname \$PKGBUILD)
                echo \"Building package in \$dir\"
                cd \$dir && makepkg -si --noconfirm && cd -
              done
            '
            echo 'List workspace files:'
            ls -R
            "
    
      - name: Upload packages to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: '**/*.pkg.tar.zst'
          
      - name: Change permissions on .git directory
        run: |
          sudo chown -R $USER:$USER .git
          
      - name: Commit new packages to repository
        run: |
          echo secrets.TEST
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.DEPLOYING }}@github.com/Leku2020/owlArchRepo.git
          git add '**/*.pkg.tar.zst'
          git commit -m "Add compiled .pkg.tar.zst packages"
          git push origin main
