name: Build PKGBUILDs

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build PKGBUILD in Arch Linux Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
            useradd -m builder && echo 'builder:password' | chpasswd && \
            pacman -Sy --noconfirm base-devel git && \
            chown -R builder:builder /workspace && \
            su - builder -c '
              # Install dependencies without sudo, directly as builder
              pacman -Sy --noconfirm alsa-lib gtk3 libxss nss ttf-font && \
              mkdir -p /home/builder/packages && \
              find /workspace -type f -name PKGBUILD | while read PKGBUILD; do
                dir=\$(dirname \$PKGBUILD)
                echo \"Building package in \$dir\"
                export PKGDEST=/home/builder/packages
                cd \$dir && makepkg -si --noconfirm && cd -
              done
            '"
      - name: Check generated package files
        run: |
          echo "Listing generated package files:"
          ls /home/builder/packages
          
      - name: Upload packages to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: '/home/builder/packages/*.pkg.tar.xz'

      - name: Commit new packages to repository
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "github-actions@github.com"
          message: "Add compiled .pkg.tar.xz packages"
          add: '/home/builder/packages/*.pkg.tar.xz'
