name: Build PKGBUILDs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos un runner de Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies for Arch Linux build
        run: |
          sudo apt update
          sudo apt install -y wget curl git
          sudo apt install -y pacman
          sudo pacman -Sy --noconfirm base-devel
          sudo pacman -Sy --noconfirm git

      - name: Build PKGBUILD
        run: |
          for dir in */; do
            if [[ -f "$dir/PKGBUILD" ]]; then
              echo "Building package in $dir"
              cd "$dir"
              makepkg -si --noconfirm 
              cd ..
            fi
          done

      - name: Upload packages to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: '**/*.pkg.tar.xz'

      - name: Commit new packages to repository
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "github-actions@github.com"
          message: "Add compiled .pkg.tar.xz packages"
          add: '**/*.pkg.tar.xz'
